config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'ads#index', as: 'home'
  resource :profile
  resources :ads do
    get "show_user_ads", on: :collection
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new(role: :guest) # guest user (not logged in)
    if user.role.guest?
      can :read, :all
    elsif user.role.user?
      can :manage, Ad, user_id: user.id
    elsif user.role.admin?
      can :manage, :all
      cannot :create, Ad
      cannot :update, Ad
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
  belongs_to :user
  belongs_to :type
  has_many :images, dependent: :destroy

  extend Enumerize
  enumerize :status, in: [:draft, :new]

  accepts_nested_attributes_for :images, :allow_destroy => true

  validates :body, presence: true, length: {minimum: 5,maximum: 1000}
  validates :status, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :ad
  #mount_uploader :name, ImageUploader

end

app/models/type.rb
class Type < ApplicationRecord
  has_many :ads
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ads
  mount_uploader :avatar, ImageUploader
  extend Enumerize
  enumerize :role, in: [:guest,:user, :admin], default: :user


  validates :first_name, presence: false, allow_blank: true, length: {minimum: 1}
  validates :second_name, presence: false, allow_blank: true, length: {minimum: 1}



  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:confirmable
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  load_and_authorize_resource
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  def index
    @ads = Ad.all.paginate(:per_page => 3, :page => params[:page])
  end

  def show_user_ads
    @ads = current_user.ads.all.paginate(:per_page => 3, :page => params[:page])
  end

  def show

  end

  def new
    @ad = Ad.new
    @ad.images.build
    @types = Type.all
  end

  def create
    @ad = Ad.new(ad_params)
    @ad.user_id = current_user.id
    if @ad.save
      redirect_to home_path
    else
      @types = Type.all
      render "new"
    end
  end

  def edit
    unless @ad.status.draft?
      redirect_to home_path
    end
    @types = Type.all
  end

  def update
    if @ad.update(ad_params)
      redirect_to home_path
    else
      render "edit"
    end
  end

  def destroy
    @ad.destroy
    redirect_to home_path
  end

  def set_ad
    @ad = Ad.find(params[:id])
  end

  private

  def ad_params
    params.require(:ad).permit(:body,
                               :image,
                               :status,
                               :type_id,
                               :images_attributes => [:name, :_destroy, :id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = t("access_denied")
    redirect_to home_path
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile

  def show

  end

  def edit

  end

  def update
    if @profile.update(profile_params)
      redirect_to profile_path
    else
      render "edit"
    end
  end

  def set_profile
    @profile = current_user
  end
  def profile_params
    params.require(:profile).permit(:first_name,
                                    :second_name,
                                    :avatar)
  end
end

app/helpers/ads_helper.rb
module AdsHelper
  def get_class(ad)
    if ad.status.draft?
      "text-secondary"
    else
      "text-success"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def get_avatar
    if @profile.avatar?
      @profile.avatar_url(:thumb)
    else
      "avatar.jpeg"
    end
  end
end

app/views/ads/_ad.html.erb
<div class="card-header">
  <h4 class="my-0 font-weight-normal"><%= ad.type.name %></h4>
</div>
<div class="card-body">
  <p style="text-overflow: ellipsis;"><%= (ad.body.html_safe).truncate_words(20) %></p>
</div>
<%= link_to t('ads.index.show_more'), ad_path(ad), style: 'bottom: 0;', class: 'btn btn-lg btn-block btn-primary mb-4' %>

app/views/ads/_form.html.erb
<%= simple_form_for(@ad) do |form| %>
  <%= form.input :body %>
  <%= form.input :type_id, collection: @types, default: @types.first %>
  <%= form.input :status, as: :radio_buttons %>
  <%= nested_form_for(@ad, html: {class: 'form-inline'}) do |nested| %>
    <%= nested.fields_for :images do |image| %>
      <%= image.file_field :name %>
      <%= image.link_to_remove t("ads.new.remove_image") %>
    <% end %>
    <p><%= nested.link_to_add t("ads.new.add_image"), :images %></p>
    <%= form.button :submit, class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/ads/edit.html.erb
<h2><%= t('.head') %></h2>
<%= javascript_include_tag "nested_form" %>
<%= simple_form_for(@ad, html: {miltipart: true}, url: ad_path, method: :patch) do |form| %>
  <%= form.input :body %>
  <%= form.input :type_id, collection: @types, default: @types.first %>
  <%= nested_form_for(@ad, html: {class: 'form-inline'}) do |nested| %>
    <%= nested.fields_for :images do |image| %>
      <% if image.object.new_record? %>
        <%= image.file_field :name %>
      <% else %>
        <%= image.object.name %>
        <%#= image_tag image.object.name.url %>
        <%= image.check_box :_destroy %>
      <% end %>
      <%= image.link_to_remove t("ads.new.remove_image") %>
    <% end %>
    <p><%= nested.link_to_add t("ads.new.add_image"), :images %></p>
    <%= form.button :submit, class: 'btn btn-success' %>
  <% end %>
<% end %>

app/views/ads/index.html.erb
<div class="card-deck mb-3 text-center">
  <%= @ads.find_each do |ad| %>
    <div class="card mb-4 shadow-sm">
      <div>
        <%= link_to t(".destroy"), ad_path(ad),
                    {style: 'color: red', method: :delete,
                     data: {confirm: t("confirmation")}} if can? :destroy, ad %>
      </div>
      <%= render "ad", ad: ad %>
    </div>
  <% end %>
</div>
<%= will_paginate @ads %>

app/views/ads/new.html.erb
<h2><%= t('.head') %></h2>
<%= javascript_include_tag "nested_form" %>
<%= render "form" %>

app/views/ads/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= @ad.body %>
      <%= @ad.images.find_each do |image| %>
        <%= image.name %>
        <%#= image_tag image.name.url %>
      <% end %>
    </div>
  </div>
</div>

app/views/ads/show_user_ads.html.erb
<div class="card-deck mb-3 text-center">
  <%= @ads.find_each do |ad| %>
    <div class="card mb-4 shadow-sm">
      <div>
        <%= link_to t(".edit"), edit_ad_path(ad) if ad.status.draft? %>
        <%= link_to t(".destroy"), ad_path(ad),
                    {style: 'color: red', method: :delete,
                     data: {confirm: t("confirmation")}} %>
      </div>
      <%= render "ad", ad: ad %>
      <h5 class=<%= get_class(ad) %>><%= t(".status",status:ad.status) %></h5>
    </div>
  <% end %>
</div>
<%= will_paginate @ads %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t(".title") %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal"><%= link_to t(".home_page"), home_path %></h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to t(".my_ads"), show_user_ads_ads_path, {:class => "p-2 text-dark"} if can? :show_user_ads, Ad  %>
    <%= link_to t(".create_ad"), new_ad_path, {:class => "p-2 text-dark"} if can? :create, Ad %>
    <% if user_signed_in? %>
      <%= link_to t(".profile"), profile_path, {:class => "p-2 text-dark"} %>

      <%= link_to t(".sign_out"), destroy_user_session_path, {:class => "btn btn-outline-danger", :method => :delete} %>
    <% else %>
      <%= link_to t(".log_in"), new_user_session_path, {:class => "btn btn-outline-primary"} %>
    <% end %>
  </nav>
</div>

<div class="container">
  <%= yield %>
</div>
<footer class="my-5 pt-5 ">
  <hr>
  <div class="text-muted text-center text-small">
    <p class="mb-1">&copy; 2019 Ads</p>
  </div>
</footer>
</body>
</html>

app/views/profiles/edit.html.erb
<h2><%= t(".title") %></h2>
<%= form_for :profile, url: profile_path, method: :patch do |f| %>
  <% if @profile.errors.any? %>
    <% @profile.errors.full_messages.each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  <% else %>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label"><%= t(".first_name") %></label>
      <%= f.text_field :first_name, {autocomplete: "first_name",
                                     :class => "col-3 mb-2 form-control"} %>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label"><%= t(".second_name") %></label>
      <%= f.text_field :second_name, {autocomplete: "second_name",
                                      :class => "col-3 mb-2 form-control"} %>
    </div>
    <hr>
    <label class="col-sm-2 col-form-label"><%= t(".avatar") %></label>
    <p class="custom-file">
      <%= f.file_field :avatar, {:class => "custom-file-label "} %>
    </p>
    <%= f.submit t(".submit"), {:class => "mt-2 mb-2 btn btn-success"} %>
  <% end %>
<% end %>

app/views/profiles/show.html.erb
<h2 class="text-center"><%= t(".title") %></h2>
<div class="container">
  <div class="row">
    <div class="col-3" style="margin-top: 2%;">
      <p><%= image_tag get_avatar, :style => "border-radius: 50%;" %></p>
    </div>
    <div class="col-5">
      <h3 class="text-left" style="color:white; margin-top: 20%;">
        <strong>
          <%= @profile.first_name %>
          <%= @profile.second_name %>
        </strong>
      </h3>
      <%= link_to t(".edit"), edit_profile_path, {class: "btn btn-success"} %>
      <%= link_to t(".edit_password"), edit_user_registration_path, { class: "btn btn-primary"} %>
    </div>
  </div>
</div>
<hr>